name: Clang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
       sudo apt install clang autoconf libpcap-dev libssl-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure CC=/usr/bin/clang
    - name: make
      run: make
